#preload= /home/kyrcovarick/Imágenes/tux_1920x1080.png

#wallpaper = , /home/kyrcovarick/Imágenes/tux_1920x1080.png

preload= /home/kyrcovarick/Imágenes/city.png

wallpaper = , /home/kyrcovarick/Imágenes/city.png


